apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
        - name: mario
          image: 985124894155.dkr.ecr.us-east-1.amazonaws.com/mario-game:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
