name: Terraform + Build + Deploy Mario

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: mario-app
  EKS_CLUSTER_NAME: mario-cluster
  K8S_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::985124894155:role/github-actions-eks
        aws-region: ${{ env.AWS_REGION }}
        - name: Verify AWS identity
  run: aws sts get-caller-identity


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Apply (create infra if missing)
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./app
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          985124894155.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 985124894155.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        severity: HIGH,CRITICAL
        exit-code: 1

    - name: Push image to ECR
      run: |
        docker push 985124894155.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/mario \
          mario=985124894155.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }} \
          -n $K8S_NAMESPACE


